第5回課題のファイルを追加
Oxie1031/RaiseTech-AWS pull request #3
Opened 2023-07-11 05:14 UTC by Oxie1031

# 概要
第5回課題のファイルを追加

2023-07-11 06:24 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！

2023-07-11 06:24 UTC, MasatoshiMizumoto commented on lecture05/images/ServerServer.png
過去の課題で指摘できてなかったらすいません！
Railsアプリケーションにアップした画像が正しく表示されてないままですね。
これNGなので修正お願いします！

2023-07-12 05:58 UTC, Oxie1031 commented on lecture05/images/ServerServer.png
ありがとうございます！
7334d9d38b422a0ed6cf71cfa8fb72979c253322
こちらのコミットにて修正いたしました！

2023-07-12 06:48 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-07-12 23:27 UTC, merged